ALTER TABLE mtpl_leave_types 
ADD COLUMN IF NOT EXISTS leaveTypeIsPaid TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS leaveTypeIsEncashable TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS leaveTypeRequireApproval TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS leaveTypeRequireAttachment TINYINT(1) DEFAULT 0;
